name: iOS Build & TestFlight
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with: { ruby-version: '3.2' }
      - name: Install XcodeGen
        run: brew install xcodegen
      - name: Generate Xcode project
        working-directory: ios-app
        run: xcodegen generate
      - name: Install Fastlane
        run: sudo gem install fastlane --no-document
      - name: Build IPA with gym
        working-directory: ios-app
        run: |
          fastlane gym \
            --project Fotbollstranaren.xcodeproj \
            --scheme Fotbollstranaren \
            --configuration Release \
            --export_method app-store \
            --skip_profile_detection true
      - name: Submit to TestFlight (if secrets present)
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_B64: ${{ secrets.ASC_KEY_B64 }}
        working-directory: ios-app
        run: |
          if [ -z "${ASC_KEY_ID}" ] || [ -z "${ASC_ISSUER_ID}" ] || [ -z "${ASC_KEY_B64}" ]; then
            echo "ASC secrets missing, skipping submit."
            exit 0
          fi
          mkdir -p fastlane/tmp
          echo "${ASC_KEY_B64}" | base64 --decode > fastlane/tmp/AuthKey.p8
          IPA_PATH=$(ls -t *.ipa | head -n 1)
          if [ -z "$IPA_PATH" ]; then
            echo "No IPA built, aborting upload"
            exit 1
          fi
          fastlane run upload_to_testflight ipa:"$IPA_PATH" apple_id:6751473029 skip_waiting_for_build_processing:true
